### ISSUE TITLE
AssertionError: assets/Sprites-gumshoe/gumshoe-shy.gif does not exist

### ISSUE THREAD

**Issue by LuisMayo** [micah5/ace-attorney-reddit-bot#15]
Or at least is not provided in the pack described in README.md
Thanks.

**Comment by l1n** [comment]
Line 320 or so of anim.py, add these lines to fallback the asset (gumshoe-shy doesn't exist)
```
                    if not os.path.isfile(
                        default_path
                        ):
                        default_path = (
                        f"{_dir}/{current_character_name.lower()}-normal(a).gif"
```

**Comment by LuisMayo** [comment]
Thanks @l1n that's a good fix
You may want to open a PR to fix it, I'll do it myself if you don't feel like it.
Thanks!
