### ISSUE TITLE
Use on Linux

### ISSUE THREAD

**Issue by LuisMayo** [micah5/ace-attorney-reddit-bot#16]
First of all, sorry for using GitHub issues for this since it's not what they're for but I truly don't know what to do

My main problem seems to be a lack of codecs of both x264 and mp3. I've already tried to compile from source ffmpeg but it doesn't seem to work because it doesn't find mp3 encoder. I'm on debían

Just opening this issue in case someone struggled with it and has an idea of what to do

Thanks

**Comment by micah5** [comment]
Hmm, I'm running the bot on ubuntu and haven't had any issues with mp4/mp3. Sorry, not sure what could be happening.

**Comment by LuisMayo** [comment]
For some reason I can't understand, I have managed to make it work on Ubuntu (still no luck on Debian)

I'll just switch to Ubuntu
Thanks!
