### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by DUOLabs333** [micah5/ace-attorney-reddit-bot#2]
This looks interesting, but there aren't any instructions on how to use.

**Comment by micah5** [comment]
I'm going to clean up the repo and add some documentation today 👍

**Comment by micah5** [comment]
Sorry for the delay. I've added some basic documentation in [a notebook](https://github.com/micah5/ace-attorney-reddit-bot/blob/master/How_to_use_anim.py.ipynb). Far from perfect but better than nothing for now 🙈
