### ISSUE TITLE
Source for other assets

### ISSUE THREAD

**Issue by yipalber** [micah5/ace-attorney-reddit-bot#4]
I was unable to find the asset sources for certain things such as `textbox4.png`, `arrow.png`, or `objection.gif`. Is this also on [court records](http://www.court-records.net/sprites1.htm)?

I assume assets like `helperstand.png` can be found on this [page](https://aceattorney.fandom.com/wiki/Courtroom).

Much help would be appreciated :)

**Comment by micah5** [comment]
Ah yes sorry, those were some assets I ripped straight off google images. I'll clean up my directory and just dump all my assets in the repo (although I'm not sure about the legality of that.. hmm). Maybe I'll just leave a download link to them in my google drive

**Comment by jburrus1** [comment]
Any updates on this? I'd love to be able to use it for something

**Comment by micah5** [comment]
Yes, sorry. I've uploaded them to google drive and put the link in the readme :)
